version: '3.8'

services:
  # Sql Server
  sql_sv:
    image: mcr.microsoft.com/mssql/server
    container_name: sql_db_server
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'P@ss12345'
    ports:
      - '1435:1433'
    volumes:
      # Use in local {path_local}:/var/opt/mssql/ 
      # - /workspaces/db:/var/opt/mssql/ 
      - /Users/v/code/Web-1-1-24/db:/var/opt/mssql/
    restart: unless-stopped
    # user: '1000:1000'  # Uncomment only if required