// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using web_qlsv.Data;

#nullable disable

namespace web_qlsv.Migrations
{
    [DbContext(typeof(QuanLySinhVienDbContext))]
    partial class QuanLySinhVienDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("VINH")
                .UseCollation("USING_NLS_COMP")
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("web_qlsv.Models.ChuongTrinhHoc", b =>
                {
                    b.Property<string>("IdChuongTrinhHoc")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDCHUONGTRINHHOC");

                    b.Property<string>("TenChuongTrinhHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TENCHUONGTRINHHOC");

                    b.HasKey("IdChuongTrinhHoc");

                    b.HasIndex(new[] { "TenChuongTrinhHoc" }, "IX_CHUONGTRINHHOC_TENCHUONGTRINHHOC");

                    b.ToTable("CHUONGTRINHHOC", "VINH");
                });

            modelBuilder.Entity("web_qlsv.Models.ChuongTrinhHocMonHoc", b =>
                {
                    b.Property<string>("IdChuongTrinhHocMonHoc")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDCHUONGTRINHHOCMONHOC");

                    b.Property<string>("IdChuongTrinhHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDCHUONGTRINHHOC");

                    b.Property<string>("IdMonHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDMONHOC");

                    b.HasKey("IdChuongTrinhHocMonHoc");

                    b.HasIndex("IdChuongTrinhHoc");

                    b.HasIndex("IdMonHoc");

                    b.ToTable("CHUONGTRINHHOC_MONHOC", "VINH");
                });

            modelBuilder.Entity("web_qlsv.Models.DangKyDoiLich", b =>
                {
                    b.Property<string>("IdDangKyDoiLich")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDDANGKYDOILICH");

                    b.Property<string>("IdThoiGian")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDTHOIGIAN");

                    b.Property<DateTime>("ThoiGianBatDauHienTai")
                        .HasColumnType("DATE")
                        .HasColumnName("THOIGIANBATDAUHIENTAI");

                    b.Property<DateTime>("ThoiGianBatDauMoi")
                        .HasColumnType("DATE")
                        .HasColumnName("THOIGIANBATDAUMOI");

                    b.Property<DateTime>("ThoiGianKetThucHienTai")
                        .HasColumnType("DATE")
                        .HasColumnName("THOIGIANKETTHUCHIENTAI");

                    b.Property<DateTime>("ThoiGianKetThucMoi")
                        .HasColumnType("DATE")
                        .HasColumnName("THOIGIANKETTHUCMOI");

                    b.Property<decimal>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("TRANGTHAI")
                        .HasDefaultValueSql("-1 ");

                    b.HasKey("IdDangKyDoiLich");

                    b.HasIndex("IdThoiGian");

                    b.HasIndex(new[] { "ThoiGianBatDauHienTai" }, "IX_DANGKYDOILICH_THOIGIANBATDAUHIENTAI");

                    b.HasIndex(new[] { "ThoiGianBatDauMoi" }, "IX_DANGKYDOILICH_THOIGIANBATDAUMOI");

                    b.HasIndex(new[] { "ThoiGianKetThucHienTai" }, "IX_DANGKYDOILICH_THOIGIANKETTHUCHIENTAI");

                    b.HasIndex(new[] { "ThoiGianKetThucMoi" }, "IX_DANGKYDOILICH_THOIGIANKETTHUCMOI");

                    b.HasIndex(new[] { "TrangThai" }, "IX_DANGKYDOILICH_TRANGTHAI");

                    b.ToTable("DANGKYDOILICH", "VINH");
                });

            modelBuilder.Entity("web_qlsv.Models.DangKyNguyenVong", b =>
                {
                    b.Property<string>("IdDangKyNguyenVong")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDDANGKYNGUYENVONG");

                    b.Property<string>("IdMonHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDMONHOC");

                    b.Property<string>("IdSinhVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDSINHVIEN");

                    b.Property<decimal>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("TRANGTHAI")
                        .HasDefaultValueSql("-1 ");

                    b.HasKey("IdDangKyNguyenVong");

                    b.HasIndex("IdMonHoc");

                    b.HasIndex("IdSinhVien");

                    b.HasIndex(new[] { "TrangThai" }, "IX_DANGKYNGUYENVONG_TRANGTHAI");

                    b.ToTable("DANGKYNGUYENVONG", "VINH");
                });

            modelBuilder.Entity("web_qlsv.Models.Diem", b =>
                {
                    b.Property<string>("IdDiem")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDDIEM");

                    b.Property<decimal>("DiemKetThuc")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("DIEMKETTHUC");

                    b.Property<decimal>("DiemQuaTrinh")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("DIEMQUATRINH");

                    b.Property<decimal>("DiemTongKet")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("DIEMTONGKET");

                    b.Property<string>("IdLopHocPhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDLOPHOCPHAN");

                    b.Property<string>("IdSinhVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDSINHVIEN");

                    b.Property<decimal>("LanHoc")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("LANHOC");

                    b.HasKey("IdDiem");

                    b.HasIndex("IdLopHocPhan");

                    b.HasIndex("IdSinhVien");

                    b.HasIndex(new[] { "DiemKetThuc" }, "IX_DIEM_DIEMKETTHUC");

                    b.HasIndex(new[] { "DiemQuaTrinh" }, "IX_DIEM_DIEMQUATRINH");

                    b.HasIndex(new[] { "DiemTongKet" }, "IX_DIEM_DIEMTONGKET");

                    b.HasIndex(new[] { "LanHoc" }, "IX_DIEM_LANHOC");

                    b.ToTable("DIEM", "VINH");
                });

            modelBuilder.Entity("web_qlsv.Models.GiaoVien", b =>
                {
                    b.Property<string>("IdGiaoVien")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDGIAOVIEN");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("IdKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDKHOA");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("SODIENTHOAI");

                    b.Property<string>("TenGiaoVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TENGIAOVIEN");

                    b.HasKey("IdGiaoVien");

                    b.HasIndex("IdKhoa");

                    b.HasIndex(new[] { "Email" }, "IX_GIAOVIEN_EMAIL");

                    b.HasIndex(new[] { "SoDienThoai" }, "IX_GIAOVIEN_SODIENTHOAI");

                    b.HasIndex(new[] { "TenGiaoVien" }, "IX_GIAOVIEN_TENGIAOVIEN");

                    b.ToTable("GIAOVIEN", "VINH");
                });

            modelBuilder.Entity("web_qlsv.Models.Khoa", b =>
                {
                    b.Property<string>("IdKhoa")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDKHOA");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TENKHOA");

                    b.HasKey("IdKhoa");

                    b.HasIndex(new[] { "TenKhoa" }, "IX_KHOA_TENKHOA");

                    b.ToTable("KHOA", "VINH");
                });

            modelBuilder.Entity("web_qlsv.Models.LopHocPhan", b =>
                {
                    b.Property<string>("IdLopHocPhan")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDLOPHOCPHAN");

                    b.Property<string>("IdGiaoVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDGIAOVIEN");

                    b.Property<string>("IdMonHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDMONHOC");

                    b.Property<decimal>("SoTietHoc")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("SOTIETHOC");

                    b.Property<decimal>("SoTinChi")
                        .HasColumnType("NUMBER(38)")
                        .HasColumnName("SOTINCHI");

                    b.Property<string>("TenHocPhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TENHOCPHAN");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("DATE")
                        .HasColumnName("THOIGIANBATDAU");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("DATE")
                        .HasColumnName("THOIGIANKETTHUC");

                    b.HasKey("IdLopHocPhan");

                    b.HasIndex("IdGiaoVien");

                    b.HasIndex("IdMonHoc");

                    b.HasIndex(new[] { "TenHocPhan" }, "IX_LOPHOCPHAN_TENHOCPHAN");

                    b.HasIndex(new[] { "ThoiGianBatDau" }, "IX_LOPHOCPHAN_THOIGIANBATDAU");

                    b.HasIndex(new[] { "ThoiGianKetThuc" }, "IX_LOPHOCPHAN_THOIGIANKETTHUC");

                    b.ToTable("LOPHOCPHAN", "VINH");
                });

            modelBuilder.Entity("web_qlsv.Models.MonHoc", b =>
                {
                    b.Property<string>("IdMonHoc")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDMONHOC");

                    b.Property<string>("IdKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDKHOA");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TENMONHOC");

                    b.HasKey("IdMonHoc");

                    b.HasIndex("IdKhoa");

                    b.HasIndex(new[] { "TenMonHoc" }, "IX_MONHOC_TENMONHOC");

                    b.ToTable("MONHOC", "VINH");
                });

            modelBuilder.Entity("web_qlsv.Models.PhongHoc", b =>
                {
                    b.Property<string>("IdPhongHoc")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDPHONGHOC");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("TenPhongHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("TENPHONGHOC");

                    b.HasKey("IdPhongHoc");

                    b.HasIndex(new[] { "DiaChi" }, "IX_PHONGHOC_DIACHI");

                    b.HasIndex(new[] { "TenPhongHoc" }, "IX_PHONGHOC_TENPHONGHOC");

                    b.ToTable("PHONGHOC", "VINH");
                });

            modelBuilder.Entity("web_qlsv.Models.SinhVien", b =>
                {
                    b.Property<string>("IdSinhVien")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDSINHVIEN");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("HOTEN");

                    b.Property<string>("IdChuongTrinhHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDCHUONGTRINHHOC");

                    b.Property<string>("IdKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDKHOA");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("LOP");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("DATE")
                        .HasColumnName("NGAYSINH");

                    b.HasKey("IdSinhVien");

                    b.HasIndex("IdChuongTrinhHoc");

                    b.HasIndex("IdKhoa");

                    b.HasIndex(new[] { "DiaChi" }, "IX_SINHVIEN_DIACHI");

                    b.HasIndex(new[] { "HoTen" }, "IX_SINHVIEN_HOTEN");

                    b.HasIndex(new[] { "Lop" }, "IX_SINHVIEN_LOP");

                    b.HasIndex(new[] { "NgaySinh" }, "IX_SINHVIEN_NGAYSINH");

                    b.ToTable("SINHVIEN", "VINH");
                });

            modelBuilder.Entity("web_qlsv.Models.SinhVienLopHocPhan", b =>
                {
                    b.Property<string>("IdSinhVienLopHocPhan")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDSINHVIENLOPHOCPHAN");

                    b.Property<string>("IdLopHocPhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDLOPHOCPHAN");

                    b.Property<string>("IdSinhVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDSINHVIEN");

                    b.HasKey("IdSinhVienLopHocPhan");

                    b.HasIndex("IdLopHocPhan");

                    b.HasIndex(new[] { "IdSinhVien", "IdLopHocPhan" }, "IX_SINHVIEN_LOPHOCPHAN");

                    b.ToTable("SINHVIEN_LOPHOCPHAN", "VINH");
                });

            modelBuilder.Entity("web_qlsv.Models.ThoiGian", b =>
                {
                    b.Property<string>("IdThoiGian")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDTHOIGIAN");

                    b.Property<string>("IdPhongHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDPHONGHOC");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("DATE")
                        .HasColumnName("NGAYBATDAU");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("DATE")
                        .HasColumnName("NGAYKETTHUC");

                    b.HasKey("IdThoiGian");

                    b.HasIndex("IdPhongHoc");

                    b.HasIndex(new[] { "NgayBatDau" }, "IX_THOIGIAN_NGAYBATDAU");

                    b.HasIndex(new[] { "NgayKetThuc" }, "IX_THOIGIAN_NGAYKETTHUC");

                    b.ToTable("THOIGIAN", "VINH");
                });

            modelBuilder.Entity("web_qlsv.Models.ThoiGianLopHocPhan", b =>
                {
                    b.Property<string>("IdThoiGianLopHocPhan")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDTHOIGIANLOPHOCPHAN");

                    b.Property<string>("IdLopHocPhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDLOPHOCPHAN");

                    b.Property<string>("IdThoiGian")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDTHOIGIAN");

                    b.HasKey("IdThoiGianLopHocPhan");

                    b.HasIndex("IdThoiGian");

                    b.HasIndex(new[] { "IdLopHocPhan", "IdThoiGian" }, "IX_THOIGIAN_LOPHOCPHAN");

                    b.ToTable("THOIGIAN_LOPHOCPHAN", "VINH");
                });

            modelBuilder.Entity("web_qlsv.Models.ChuongTrinhHocMonHoc", b =>
                {
                    b.HasOne("web_qlsv.Models.ChuongTrinhHoc", "IdChuongTrinhHocNavigation")
                        .WithMany("ChuongTrinhHocMonHocs")
                        .HasForeignKey("IdChuongTrinhHoc")
                        .IsRequired();

                    b.HasOne("web_qlsv.Models.MonHoc", "IdMonHocNavigation")
                        .WithMany("ChuongTrinhHocMonHocs")
                        .HasForeignKey("IdMonHoc")
                        .IsRequired();

                    b.Navigation("IdChuongTrinhHocNavigation");

                    b.Navigation("IdMonHocNavigation");
                });

            modelBuilder.Entity("web_qlsv.Models.DangKyDoiLich", b =>
                {
                    b.HasOne("web_qlsv.Models.ThoiGian", "IdThoiGianNavigation")
                        .WithMany("DangKyDoiLichs")
                        .HasForeignKey("IdThoiGian")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdThoiGianNavigation");
                });

            modelBuilder.Entity("web_qlsv.Models.DangKyNguyenVong", b =>
                {
                    b.HasOne("web_qlsv.Models.MonHoc", "IdMonHocNavigation")
                        .WithMany("DangKyNguyenVongs")
                        .HasForeignKey("IdMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_qlsv.Models.SinhVien", "IdSinhVienNavigation")
                        .WithMany("DangKyNguyenVongs")
                        .HasForeignKey("IdSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdMonHocNavigation");

                    b.Navigation("IdSinhVienNavigation");
                });

            modelBuilder.Entity("web_qlsv.Models.Diem", b =>
                {
                    b.HasOne("web_qlsv.Models.LopHocPhan", "IdLopHocPhanNavigation")
                        .WithMany("Diems")
                        .HasForeignKey("IdLopHocPhan")
                        .IsRequired();

                    b.HasOne("web_qlsv.Models.SinhVien", "IdSinhVienNavigation")
                        .WithMany("Diems")
                        .HasForeignKey("IdSinhVien")
                        .IsRequired();

                    b.Navigation("IdLopHocPhanNavigation");

                    b.Navigation("IdSinhVienNavigation");
                });

            modelBuilder.Entity("web_qlsv.Models.GiaoVien", b =>
                {
                    b.HasOne("web_qlsv.Models.Khoa", "IdKhoaNavigation")
                        .WithMany("GiaoViens")
                        .HasForeignKey("IdKhoa")
                        .IsRequired();

                    b.Navigation("IdKhoaNavigation");
                });

            modelBuilder.Entity("web_qlsv.Models.LopHocPhan", b =>
                {
                    b.HasOne("web_qlsv.Models.GiaoVien", "IdGiaoVienNavigation")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("IdGiaoVien")
                        .IsRequired();

                    b.HasOne("web_qlsv.Models.MonHoc", "IdMonHocNavigation")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("IdMonHoc")
                        .IsRequired();

                    b.Navigation("IdGiaoVienNavigation");

                    b.Navigation("IdMonHocNavigation");
                });

            modelBuilder.Entity("web_qlsv.Models.MonHoc", b =>
                {
                    b.HasOne("web_qlsv.Models.Khoa", "IdKhoaNavigation")
                        .WithMany("MonHocs")
                        .HasForeignKey("IdKhoa")
                        .IsRequired();

                    b.Navigation("IdKhoaNavigation");
                });

            modelBuilder.Entity("web_qlsv.Models.SinhVien", b =>
                {
                    b.HasOne("web_qlsv.Models.ChuongTrinhHoc", "IdChuongTrinhHocNavigation")
                        .WithMany("SinhViens")
                        .HasForeignKey("IdChuongTrinhHoc")
                        .IsRequired();

                    b.HasOne("web_qlsv.Models.Khoa", "IdKhoaNavigation")
                        .WithMany("SinhViens")
                        .HasForeignKey("IdKhoa")
                        .IsRequired();

                    b.Navigation("IdChuongTrinhHocNavigation");

                    b.Navigation("IdKhoaNavigation");
                });

            modelBuilder.Entity("web_qlsv.Models.SinhVienLopHocPhan", b =>
                {
                    b.HasOne("web_qlsv.Models.LopHocPhan", "IdLopHocPhanNavigation")
                        .WithMany("SinhVienLopHocPhans")
                        .HasForeignKey("IdLopHocPhan")
                        .IsRequired();

                    b.HasOne("web_qlsv.Models.SinhVien", "IdSinhVienNavigation")
                        .WithMany("SinhVienLopHocPhans")
                        .HasForeignKey("IdSinhVien")
                        .IsRequired();

                    b.Navigation("IdLopHocPhanNavigation");

                    b.Navigation("IdSinhVienNavigation");
                });

            modelBuilder.Entity("web_qlsv.Models.ThoiGian", b =>
                {
                    b.HasOne("web_qlsv.Models.PhongHoc", "IdPhongHocNavigation")
                        .WithMany("ThoiGians")
                        .HasForeignKey("IdPhongHoc")
                        .IsRequired();

                    b.Navigation("IdPhongHocNavigation");
                });

            modelBuilder.Entity("web_qlsv.Models.ThoiGianLopHocPhan", b =>
                {
                    b.HasOne("web_qlsv.Models.LopHocPhan", "IdLopHocPhanNavigation")
                        .WithMany("ThoiGianLopHocPhans")
                        .HasForeignKey("IdLopHocPhan")
                        .IsRequired();

                    b.HasOne("web_qlsv.Models.ThoiGian", "IdThoiGianNavigation")
                        .WithMany("ThoiGianLopHocPhans")
                        .HasForeignKey("IdThoiGian")
                        .IsRequired();

                    b.Navigation("IdLopHocPhanNavigation");

                    b.Navigation("IdThoiGianNavigation");
                });

            modelBuilder.Entity("web_qlsv.Models.ChuongTrinhHoc", b =>
                {
                    b.Navigation("ChuongTrinhHocMonHocs");

                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("web_qlsv.Models.GiaoVien", b =>
                {
                    b.Navigation("LopHocPhans");
                });

            modelBuilder.Entity("web_qlsv.Models.Khoa", b =>
                {
                    b.Navigation("GiaoViens");

                    b.Navigation("MonHocs");

                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("web_qlsv.Models.LopHocPhan", b =>
                {
                    b.Navigation("Diems");

                    b.Navigation("SinhVienLopHocPhans");

                    b.Navigation("ThoiGianLopHocPhans");
                });

            modelBuilder.Entity("web_qlsv.Models.MonHoc", b =>
                {
                    b.Navigation("ChuongTrinhHocMonHocs");

                    b.Navigation("DangKyNguyenVongs");

                    b.Navigation("LopHocPhans");
                });

            modelBuilder.Entity("web_qlsv.Models.PhongHoc", b =>
                {
                    b.Navigation("ThoiGians");
                });

            modelBuilder.Entity("web_qlsv.Models.SinhVien", b =>
                {
                    b.Navigation("DangKyNguyenVongs");

                    b.Navigation("Diems");

                    b.Navigation("SinhVienLopHocPhans");
                });

            modelBuilder.Entity("web_qlsv.Models.ThoiGian", b =>
                {
                    b.Navigation("DangKyDoiLichs");

                    b.Navigation("ThoiGianLopHocPhans");
                });
#pragma warning restore 612, 618
        }
    }
}
