name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Kích hoạt triển khai khi có đẩy mã lên nhánh main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' # Sử dụng phiên bản .NET mà dự án yêu cầu

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet publish -c Release -o output

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output/wwwroot # Thư mục chứa các file đã build
